import { test } from "node:test";
import assert from "node:assert/strict";
import {
  filterWorkJobs,
  fmtSizeMb,
  groupWork,
  isWorkView,
  parseWorkJobs,
} from "./musicwork.ts";

const HEADER = "category,client,job,year,last_active,files,size_mb,flags";

function bodyWith(rows: string[], header = HEADER): string {
  return ["Generated by music_work_scan.py.", "", "```csv", header, ...rows, "```", ""].join("\n");
}

// the real sheet's shape: three categories, four clients, three years, one
// flagged row, one 0-byte job
const SAMPLE = bodyWith([
  "MASTERING,Mira,Fern Static [from sessions 2025],2025,2026-07-29,51,1392,name 2025 vs files 2026",
  "MASTERING,Mira,mira master v2,2026,2026-03-02,12,340,",
  "MASTERING,Ada Voss,Voss Signal,2026,2026-06-13,318,23949,",
  "MIXING,Juno Marek,ep1,2026,2026-03-23,272,48179,",
  "MIXING,Mira,mira adjust Project,2026,2026-01-06,3,0,",
  "OWN WORK,COLLABS,Lila,2024,2024-01-23,54,3880,",
]);

test("parseWorkJobs: typed rows, every column mapped by name", () => {
  const jobs = parseWorkJobs(SAMPLE);
  assert.equal(jobs.length, 6);
  assert.deepEqual(jobs[0], {
    category: "MASTERING",
    client: "Mira",
    job: "Fern Static [from sessions 2025]",
    year: "2025",
    lastActive: "2026-07-29",
    files: 51,
    sizeMb: 1392,
    flags: "name 2025 vs files 2026",
    idx: 0,
  });
  assert.equal(jobs[4].sizeMb, 0);
  assert.equal(jobs[4].flags, "");
});

test("parseWorkJobs: column order is free and case-insensitive", () => {
  const jobs = parseWorkJobs(
    bodyWith(["2024,Mira,MASTERING,a job,7"], "Year,Client,CATEGORY,job,files"),
  );
  assert.equal(jobs.length, 1);
  assert.deepEqual(
    { c: jobs[0].category, cl: jobs[0].client, j: jobs[0].job, y: jobs[0].year, f: jobs[0].files },
    { c: "MASTERING", cl: "Mira", j: "a job", y: "2024", f: 7 },
  );
  // columns the scanner didn't write read as empty/0, not as errors
  assert.equal(jobs[0].lastActive, "");
  assert.equal(jobs[0].sizeMb, 0);
});

test("parseWorkJobs: quoted commas in job and flag text survive", () => {
  const jobs = parseWorkJobs(
    bodyWith(['MIXING,Mira,"ep1, alt take",2025,2025-02-01,3,10,"name 2024, files 2025"']),
  );
  assert.equal(jobs[0].job, "ep1, alt take");
  assert.equal(jobs[0].flags, "name 2024, files 2025");
});

test("parseWorkJobs: malformed rows are skipped, not errors", () => {
  const jobs = parseWorkJobs(
    bodyWith([
      "MASTERING,Mira,,2025,2025-01-01,1,1,", // no job name
      "MASTERING,Mira,undated,,2025-01-01,1,1,", // no year
      "MASTERING,Mira,bad year,25,2025-01-01,1,1,", // not a 4-digit year
      "MASTERING,Mira,junk counts,2025,2025-01-01,many,huge,", // non-numeric counts
      "MASTERING,Mira,keeper,2025,2025-01-01,2,5,",
    ]),
  );
  assert.deepEqual(
    jobs.map((j) => j.job),
    ["junk counts", "keeper"],
  );
  // a non-numeric count is a 0, not a dropped job
  assert.equal(jobs[0].files, 0);
  assert.equal(jobs[0].sizeMb, 0);
});

test("parseWorkJobs: empty, fenceless and headerless bodies read as no jobs", () => {
  assert.deepEqual(parseWorkJobs(""), []);
  assert.deepEqual(parseWorkJobs("Just prose, no sheet here.\n"), []);
  assert.deepEqual(parseWorkJobs(bodyWith([])), []);
  // a sheet without job/year columns can't be pivoted — empty, never a throw
  assert.deepEqual(parseWorkJobs(bodyWith(["MASTERING,Mira,3"], "category,client,files")), []);
});

test("groupWork year: years descend, categories A–Z inside, jobs newest first", () => {
  const groups = groupWork(parseWorkJobs(SAMPLE), "year");
  assert.deepEqual(
    groups.map((g) => g.label),
    ["2026", "2025", "2024"],
  );
  const y2026 = groups[0];
  assert.equal(y2026.count, 4);
  // the year header's anchors: 4 jobs, 340 + 23949 + 48179 + 0 MB
  assert.equal(y2026.sizeMb, 72468);
  assert.deepEqual(
    y2026.subs.map((s) => s.label),
    ["MASTERING", "MIXING"],
  );
  // inside MASTERING/2026: Voss Signal (06-13) before mira master v2 (03-02)
  assert.deepEqual(
    y2026.subs[0].jobs.map((j) => j.job),
    ["Voss Signal", "mira master v2"],
  );
});

test("groupWork artist: clients A–Z ignoring case, their years descending", () => {
  const groups = groupWork(parseWorkJobs(SAMPLE), "artist");
  assert.deepEqual(
    groups.map((g) => g.label),
    ["Ada Voss", "COLLABS", "Juno Marek", "Mira"],
  );
  const mira = groups[3];
  assert.equal(mira.count, 3);
  assert.deepEqual(
    mira.subs.map((s) => s.label),
    ["2026", "2025"],
  );
  assert.deepEqual(
    mira.subs[0].jobs.map((j) => j.job),
    ["mira master v2", "mira adjust Project"],
  );
});

test("groupWork category: categories A–Z, years descending inside", () => {
  const groups = groupWork(parseWorkJobs(SAMPLE), "category");
  assert.deepEqual(
    groups.map((g) => g.label),
    ["MASTERING", "MIXING", "OWN WORK"],
  );
  assert.deepEqual(
    groups[0].subs.map((s) => s.label),
    ["2026", "2025"],
  );
  assert.equal(groups[0].sizeMb, 1392 + 340 + 23949);
});

test("groupWork: an empty index groups to nothing in every view", () => {
  for (const view of ["year", "artist", "category"] as const)
    assert.deepEqual(groupWork([], view), []);
});

test("groupWork: a blank client or category groups under a placeholder", () => {
  const jobs = parseWorkJobs(bodyWith([",,orphan,2025,2025-01-01,1,1,"]));
  assert.equal(groupWork(jobs, "artist")[0].label, "—");
  assert.equal(groupWork(jobs, "year")[0].subs[0].label, "—");
});

test("groupWork: a job with no last_active sorts below dated siblings", () => {
  const jobs = parseWorkJobs(
    bodyWith([
      "MASTERING,Mira,undatedjob,2025,,1,1,",
      "MASTERING,Mira,dated,2025,2025-01-01,1,1,",
    ]),
  );
  assert.deepEqual(
    groupWork(jobs, "year")[0].subs[0].jobs.map((j) => j.job),
    ["dated", "undatedjob"],
  );
});

test("filterWorkJobs: substring over client and job, case-insensitive", () => {
  const jobs = parseWorkJobs(SAMPLE);
  assert.equal(filterWorkJobs(jobs, "").length, 6);
  assert.equal(filterWorkJobs(jobs, "   ").length, 6);
  // matches the client
  assert.deepEqual(
    filterWorkJobs(jobs, "MIRA").map((j) => j.job),
    ["Fern Static [from sessions 2025]", "mira master v2", "mira adjust Project"],
  );
  // matches the job name only
  assert.deepEqual(
    filterWorkJobs(jobs, "signal").map((j) => j.client),
    ["Ada Voss"],
  );
  // the category is deliberately NOT searched — that's what the view is for
  assert.deepEqual(filterWorkJobs(jobs, "MIXING"), []);
  assert.deepEqual(filterWorkJobs(jobs, "nothing here"), []);
});

test("filterWorkJobs feeds the same grouping — filtered totals, not global", () => {
  const groups = groupWork(filterWorkJobs(parseWorkJobs(SAMPLE), "mira"), "year");
  assert.deepEqual(
    groups.map((g) => [g.label, g.count]),
    [
      ["2026", 2],
      ["2025", 1],
    ],
  );
  assert.equal(groups[0].sizeMb, 340);
});

test("fmtSizeMb: MB below a gig, one-decimal GB above, dust for zero", () => {
  assert.equal(fmtSizeMb(0), "—");
  assert.equal(fmtSizeMb(-5), "—");
  assert.equal(fmtSizeMb(NaN), "—");
  assert.equal(fmtSizeMb(340), "340 MB");
  assert.equal(fmtSizeMb(1023.6), "1024 MB");
  assert.equal(fmtSizeMb(2048), "2,0 GB");
  assert.equal(fmtSizeMb(140706), "137,4 GB");
});

test("isWorkView: only the three axes", () => {
  assert.ok(isWorkView("year"));
  assert.ok(isWorkView("artist"));
  assert.ok(isWorkView("category"));
  assert.equal(isWorkView("client"), false);
  assert.equal(isWorkView(""), false);
});
