#!/usr/bin/env bash
# Portable shared Cargo target for local Substrate builds.
#
# Cargo does not expand $HOME or ~ in .cargo/config.toml, so a CHECKED-IN
# absolute target-dir ties every clone to one account — that is why the repo
# has none and .gitignore keeps one from ever being committed again. The
# default therefore lives in a shell entry point: npm's Tauri command and the
# repo scripts source this file, while CI/release CARGO_TARGET_DIR overrides
# remain authoritative (the process env beats cargo config on every machine).
#
# A shell entry point only reaches builds that go through one. A bare
# `cargo build` in a worktree still wrote a private src-tauri/target — 23 of 78
# worktrees, ~119G duplicated. So the wrappers now also PIN the current
# checkout: substrate_pin_cargo_target_config writes a machine-local, gitignored
# <checkout>/.cargo/config.toml holding this machine's absolute shared path. Generated, never committed, so no other machine or account ever
# sees it — the header's original constraint holds, it just moved from "no
# config file" to "no config file in git". Only the machine default is written:
# an explicit CARGO_TARGET_DIR belongs to the process that set it, and
# SUBSTRATE_NO_CARGO_PIN=1 turns the write off outright.

substrate_use_shared_cargo_target() {
  if [[ -z "${CARGO_TARGET_DIR:-}" ]]; then
    CARGO_TARGET_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/substrate-cargo-target"
  fi
  export CARGO_TARGET_DIR
}

# Marks the generated file as ours. Anything without this line is an operator's
# own config and is left untouched, however stale its target-dir.
SUBSTRATE_CARGO_CONFIG_MARKER='# generated by scripts/lib/cargo-target.sh — machine-local, never commit'

# Writes <checkout>/.cargo/config.toml so builds started outside the wrappers
# land in the shared cache too. Quiet and idempotent; never fatal — a build
# that cannot be pinned still builds.
substrate_pin_cargo_target_config() {
  # An ad-hoc CARGO_TARGET_DIR is for THIS process, not for the checkout: a
  # gate run or a one-off override must not be what later bare builds inherit.
  # Only the machine default is ever written down.
  [[ -z "${CARGO_TARGET_DIR:-}" && -z "${SUBSTRATE_NO_CARGO_PIN:-}" ]] || return 0

  # The checkout that owns THIS file, not the caller's cwd: the pin belongs to
  # the tree whose scripts are running, wherever the build was started from.
  local root config desired
  root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." 2>/dev/null && pwd -P)" || return 0
  # `.git` is a dir in a clone and a file in a worktree; either means a real
  # checkout, and a release tarball without one is left alone.
  [[ -n "$root" && -e "$root/.git" && -e "$root/src-tauri/Cargo.toml" ]] || return 0

  substrate_use_shared_cargo_target
  config="$root/.cargo/config.toml"
  desired="$SUBSTRATE_CARGO_CONFIG_MARKER
[build]
target-dir = \"$CARGO_TARGET_DIR\"
"

  if [[ -e "$config" ]]; then
    [[ "$(head -1 "$config" 2>/dev/null)" == "$SUBSTRATE_CARGO_CONFIG_MARKER" ]] || return 0
    [[ "$(cat "$config" 2>/dev/null)" == "$desired" ]] && return 0
  fi

  mkdir -p "$root/.cargo" 2>/dev/null || return 0
  printf '%s' "$desired" > "$config" 2>/dev/null || return 0
  return 0
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  if [[ "${1:-}" == "--pin" ]]; then
    substrate_pin_cargo_target_config
    printf 'cargo-target: pinned %s\n' "${CARGO_TARGET_DIR:-?}"
    exit 0
  fi
  if [[ $# -eq 0 ]]; then
    printf 'cargo-target.sh: command required (or --pin)\n' >&2
    exit 2
  fi
  substrate_pin_cargo_target_config
  substrate_use_shared_cargo_target
  exec "$@"
fi
